### ISSUE TITLE
Update MySQL? Version 8.0.30+

### ISSUE THREAD

**Issue by royduin** [TablePlus/DBngin#103]
8.0.27 was released at 2021-10-19, the latest release at the moment of writing this issue is 8.0.33. I need the update as of this bug: https://bugs.mysql.com/bug.php?id=106621

How? Or how can I contribute to add a new version?

**Comment by huyphams** [comment]
Hi @royduin we will add the new mysql this weekend. Thanks 👍

**Comment by royduin** [comment]
That's fast! Looking forward to the update! 🚀
