### ISSUE TITLE
Update existing MySQL server from 8.0.27 to 8.0.33

### ISSUE THREAD

**Issue by royduin** [TablePlus/DBngin#105]
With the latest update MySQL 8.0.33 is available, but is it possible to upgrade the existing MySQL 8.0.27 server to 8.0.33?

**Comment by huyphams** [comment]
Hi @royduin the simplest solution is that you can dump the data and restore it to the new instance.

**Comment by royduin** [comment]
Alright, I'll do that, thanks 👍🏻
