### ISSUE TITLE
How can I change my redis config

### ISSUE THREAD

**Issue by minesunny** [TablePlus/DBngin#107]

**Comment by gorkijatt** [comment]
i had done using redis-cli commands : 

- redis-cli
- 127.0.0.1:6379> AUTH PASSWORD
- 127.0.0.1:6379> CONFIG SET requirepass "mypass"
   OK


now you're password has been setup and you can authenticate using

- redis-cli
- 127.0.0.1:6379> AUTH mypass

**Comment by minesunny** [comment]
> 

I have tried this way,it didn't work;

**Comment by gorkijatt** [comment]
Can you give me some detail : 

1. Your operating system ?
2. Have you set environment variable for redis ?
3. redis-cli command working in terminal ?
4. Are you using tableplus ?
5. In what type of project you are using redis ?
