### ISSUE TITLE
Can't connect to MySQL from Navicat

### ISSUE THREAD

**Issue by mharding7va** [TablePlus/DBngin#112]
Connection Failed

1. Driver (Ex: PostgreSQL 10.0):
MySQL 8

2. DBngin build number:
6.6

3. macOS version:
13.4.1

4. The steps to reproduce this issue:
Authentication plugin 'caching_sha2_password' cannot be loaded: dlopen(../Frameworks/caching_sha2_password.so, 0x0002): tried: '../Frameworks/caching_sha2_password.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS../Frameworks/caching_sha2_password.so' (no such file), '/Applications/Navicat for MySQL.app/Contents/Frameworks/../Frameworks/caching_sha2_password.so' (no such file), '/Applications/Navicat for MySQL.app/Contents/Frameworks/../Frameworks/caching_sha2_password.so' (no such file), '/usr/l

**Comment by huyphams** [comment]
Hi @mharding7va it's the Navicat issue
