### ISSUE TITLE
Upgrade from MySQL 5.7 to 8.0

### ISSUE THREAD

**Issue by iugo-robert** [TablePlus/DBngin#116]
Is there a nice way using DBngin to upgrade my existing MySQL database from version 5.7 to 8.0?

**Comment by huyphams** [comment]
You can dump database and then import it to MySQL 8.0 @iugo-robert

**Comment by iugo-robert** [comment]
@huyphams To your knowledge are there any tools to get the mysqldump file to import without error?

**Comment by huyphams** [comment]
You can use the backup/restore in https://tableplus.com, it's free and does not require a license.
