### ISSUE TITLE
Can't Remove Services

### ISSUE THREAD

**Issue by krlmrr** [TablePlus/DBngin#118]
Please fill out the detail below, it helps me investigate the bug:

1. Driver (Ex: PostgreSQL 10.0):
MySQL 5.7.23
MySQL 8.0.33

2. DBngin build number:
6.8

3. macOS version:
14

4. The steps to reproduce this issue:
    1. Start a new service. 
    2. Attempt to delete the new service.

**Comment by krlmrr** [comment]
If It helps this is a Apple M2 Pro chipset.

**Comment by huyphams** [comment]
Hi @krlmrr does the service already started or it is still downloading the binaries? Did you highlight it or just right click? Could you make me a gif please.

**Comment by huyphams** [comment]
Never mind, I can reproduce it now.

**Comment by huyphams** [comment]
Pushed a new update which fixes this issue. Thanks!
