### ISSUE TITLE
Can't open MySQL 8 server with SequelPro

### ISSUE THREAD

**Issue by fanpero87** [TablePlus/DBngin#124]
Please fill out the detail below, it helps me investigate the bug:

1. Driver (Ex: PostgreSQL 10.0):
MySQL 8.0.33 Intel|ARM

3. DBngin build number:
Sequel Pro 1.12
DBngin 6.9

4. macOS version:
Macbook with M2 running Sonoma 14.1.1

5. The steps to reproduce this issue:
I made two MySQL servers. Once running version 5.7Intel on port 3306 and another running 8.0.33 Intel|ARM on port 3307.
I can connect on localhost (12.0.0.1) to version 5 but not to version 8.
Here is the error I get:
```
Unable to connect to host 127.0.0.1, or the request timed out.

Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).

MySQL said: Authentication plugin 'caching_sha2_password' cannot be loaded: dlopen(/usr/local/lib/plugin/caching_sha2_password.so, 0x0002): tried: '/usr/local/lib/plugin/caching_sha2_password.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/plugin/caching_sha2_password.so' (no such file), '/usr/local/lib/plugin/caching_sha2_password.so' (no such file)
```

I tried all the other Servers but none of them work.
![Screenshot 2023-11-19 at 11 14 14 PM](https://github.com/TablePlus/DBngin/assets/65570296/5ff0b13c-1e81-4153-a20a-b085292db0d6)

I'm just wondering if the issue is due to the fact that I'm not using Tableplus.

Thanks.

**Comment by huyphams** [comment]
Hi @fanpero87  Sequel Pro does not support MySQL 8.0
TablePlus is nothing todo with this issue, we wouldn't do that thing to prevent user to use other app. They are free to choose their favoriete tool :)
