### ISSUE TITLE
Feature Request: Hide DBngin Dock Icon

### ISSUE THREAD

**Issue by abbassiddiqi** [TablePlus/DBngin#133]
I propose adding an **option to hide the DBngin icon from the dock** and interact with it solely through the menu bar icon.

This would provide a cleaner and more streamlined user experience for those who prefer minimal dock clutter.

Suggestion:

Add a checkbox or toggle switch in the Preferences menu titled "Hide Dock Icon" or "Show in Menu Bar Only."

**Comment by huyphams** [comment]
You can simply close the app, @abbassiddiqi. If we close the app (cmd + Q), it could cause more issues than convenience.
