### ISSUE TITLE
Application won't start on Mac M1

### ISSUE THREAD

**Issue by TomSenter** [TablePlus/DBngin#138]
Hi guys, my application isn't responding for some reason and I'm not sure why. I've left all the details underneath, my application was responding about 2 days ago though so really not sure what's happened.

DBngin build number: 7.0
macOS version: 12.0.1

Steps to reproduce:
I clicked update DBngin inside the application and ever since then it won't respond. I've also tried installing an older version to see if that works but it doesn't. Now whenever I click on the application it won't load or respond.

Thanks in advance!

**Comment by huyphams** [comment]
Hi @TomSenter could you please try to restart macOS and see how it goes?

**Comment by TomSenter** [comment]
@huyphams Thank you that's sorted it for me!

**Comment by huyphams** [comment]
Yeah sometimes, it's macOS issue.

Thanks for confirming.
