### ISSUE TITLE
PostGIS extension for PostgreSQL

### ISSUE THREAD

**Issue by crscnc** [TablePlus/DBngin#144]
Hi Team @TablePlus,

You guys doing a great job by releasing the DBing. I love it, and using it as my alternative to Docker Compose consumes lots of memory in my Mac.

Is it possible to add PostGIS extension for PostgreSQL?

Thank you

**Comment by huyphams** [comment]
Hi @crscnc DBngin PostgreSQL always bundled with PostGIS you may try to create PostgreSQL 14 with PostGIS.
