### ISSUE TITLE
How to uninstall what is installed by DBngin

### ISSUE THREAD

**Issue by rabol** [TablePlus/DBngin#146]
I would like to uninstall an old version of Mysql, can DBngin do that or is that a manual task ?

**Comment by huyphams** [comment]
1. Stop the server.
2. Right click > show database files => delete everything.
3. Right click > show database server binaries => delete everything.

Done!
<img width="328" alt="Screenshot 2024-06-15 at 1 08 27 AM" src="https://github.com/TablePlus/DBngin/assets/3654622/7b83f60b-63b0-40f6-913a-8a0bc1867ea0">

**Comment by huyphams** [comment]
Please remember to backup just in case you delete the wrong one.

**Comment by huyphams** [comment]
You can only delete what has been created by DBngin, not by the other apps,

**Comment by rabol** [comment]
Had not even see that menu, thanks a lot!
