### ISSUE TITLE
Add MySQL 8.4

### ISSUE THREAD

**Issue by davidbankes** [TablePlus/DBngin#147]
mysql 8.4 is the new LTS version. I have a client that wants to be able to update their install, so I'd like to be able to test against this. IS there any plan to add mysql 8.4?

**Comment by huyphams** [comment]
Yes, we will add MySQL 8.4 in the next update. Along with PostgreSQL 16.3

**Comment by mstaack** [comment]
@huyphams please also consider adding PostgreSQL 17

**Comment by huyphams** [comment]
Added PostgreSQL 17 and MySQL 8.4.2.
Thanks.
