### ISSUE TITLE
Request: Ship PostGIS extension out of the box

### ISSUE THREAD

**Issue by matthiasfeist** [TablePlus/DBngin#150]
Please fill out the detail below, it helps me investigate the bug:

1. Driver (Ex: PostgreSQL 10.0): Postgres 16.2

2. DBngin build number: 7.1

5. macOS version: 14.2.1 (23C71)

6. The steps to reproduce this issue:  Create a new Postgres 16.2 server. Open a SQL connection and execute the SQL `CREATE EXTENSION postgis;`

**Comment by huyphams** [comment]
Postgis now is a part of PostgreSQL 16.4 and PostgreSQL 17 (ARM only).
