### ISSUE TITLE
DBNgin doesnt work on Windows

### ISSUE THREAD

**Issue by countradooku** [TablePlus/DBngin#152]
Driver: Mysql
OS: windows 11

I have a fresh install and when i try to open with tableplus i get this error:

![image](https://github.com/user-attachments/assets/2c6f50b9-b0fd-4003-a931-48b9e6e0ef6a)
![image](https://github.com/user-attachments/assets/b153cf77-c713-4f54-8a89-efc629c999a1)

Also in task manger mysql is not running. i tried install reboot uninstall and anything. i cant even find log for errors
![image](https://github.com/user-attachments/assets/5e204946-7083-49e6-a112-69cf25315525)

**Comment by patuh-istizhar** [comment]
I'm experiencing the same issue. When I show the database binaries for MySQL, it opens C:\Users\Username\OneDrive\Documents, but for PostgreSQL, it successfully points to C:\Users\Username\AppData\Local\com.tinyapp.DBngin\Binaries\postgresql\16.4.1.

**Comment by kodyxgen** [comment]
I have the same problem with build 0.0.5 on windows. 
The problem in my case was that DBNgin was missing the server binaries in C:\Users\xxxxx\AppData\Local\com.tinyapp.DBngin\Binaries\mysql\8.4.0
so i downloaded  https://cdn.mysql.com/archives/mysql-8.4/mysql-8.4.0-winx64.zip unzip and copy the files in that directory and the mysql server started

Hope it helps you 2!

**Comment by akz3ro** [comment]
I have the same problem,
I solved this problem by copying the bin folder from:
C:\Program Files\MySQL\MySQL Server 8.0
to:
C:\Users\<username>\AppData\Local\com.tinyapp.DBngin\Binaries\mysql\8.4.0

**Comment by AnaelBonnafous** [comment]
I've got the same error and placing MySQL binaries in `C:\Users\xxxxx\AppData\Local\com.tinyapp.DBngin\Binaries\mysql\8.4.0` is not changing anything.

**Comment by huyphams** [comment]
Hi @AnaelBonnafous you may need to install the C++ runtime
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by JeremieMercier** [comment]
Same problem, the MySQL service does not start, because the binaries folder for MySQL is empty. 
If I download the MySQL binary and move the bin folder the service starts.

**Comment by jlabs** [comment]
Also on 0.0.5 on Windows and the `C:\Users\xxxxx\AppData\Local\com.tinyapp.DBngin\Binaries\mysql\8.4.0` folder was empty.

Followed @kodyxgen steps and now works.

**Comment by AnaelBonnafous** [comment]
> Hi @AnaelBonnafous you may need to install the C++ runtime https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

I already had it, but update using your link just in case.
Actually, my issue was that I misplaced the files in bin folder, `Binaries\mysql\8.4.0\{files}` instead of `Binaries\mysql\8.4.0\bin\{files}`.
Now fixed, thank you all 👍

**Comment by huyphams** [comment]
Please try update the app to build 0.0.6 it should fix the issue. Let me know if you're still seeing it.

**Comment by mityukov** [comment]
> Please try update the app to build 0.0.6

Installed DBNgin today and the error is the same when trying to connect to the database via DBNgin::TablePlus

Note: DB service is indicated as running in DBNgin

**Comment by MuhammadM1998** [comment]
I encountered the same issue on Windows using v1.3.2.

The MySQL service is marked as running. Clicking 'stop' shows a spinner, then it returns to 'Running'.
My `AppData\Local\com.tinyapp.DBngin\Binaries\mysql\8.4.2` folder is not empty and already has contents.
Deleting the service and creating another one works but I'd have to recreate the dbs, migrate, and seed them every time.

![Image](https://github.com/user-attachments/assets/9c928736-9cc0-403c-8fdd-d789d336e50d)

![Image](https://github.com/user-attachments/assets/b63920c7-c83c-4066-b8f3-fde73ef3e620)

**Comment by nangtrongvuon** [comment]
> I encountered the same issue on Windows using v1.3.2.
> 
> The MySQL service is marked as running. Clicking 'stop' shows a spinner, then it returns to 'Running'. My `AppData\Local\com.tinyapp.DBngin\Binaries\mysql\8.4.2` folder is not empty and already has contents. Deleting the service and creating another one works but I'd have to recreate the dbs, migrate, and seed them every time.
> 
> ![Image](https://github.com/user-attachments/assets/9c928736-9cc0-403c-8fdd-d789d336e50d)
> 
> ![Image](https://github.com/user-attachments/assets/b63920c7-c83c-4066-b8f3-fde73ef3e620)

Hello, could you tell me more about your setup? Are you using a config? Do you have a password set for the mysql root user? Can you open the DB in TablePlus? (using the button next to the Stop button)

**Comment by MuhammadM1998** [comment]
> Hello, could you tell me more about your setup? Are you using a config? Do you have a password set for the mysql root user? Can you open the DB in TablePlus? (using the button next to the Stop button)

I have no custom config nor password for the db. No TablePlus fails to connect to the DB too, it also not present in task manager services.

**Comment by BirdEyeview1000** [comment]
Same issue, I uninstalled and reinstalled many times. The binaries are in the right place and even works when you create a new database, but the old one the mysql binaries are crashing, the new one they stay running. Are there any logs or anything to see why these are crashing?

**Comment by nangtrongvuon** [comment]
> Same issue, I uninstalled and reinstalled many times. The binaries are in the right place and even works when you create a new database, but the old one the mysql binaries are crashing, the new one they stay running. Are there any logs or anything to see why these are crashing?

There should be a log located in the database's data folder (Right click on database -> Open data directory). For MySQL it should be named `mysqld.local.err`. Can you check that and provide me with what you see?

**Comment by BirdEyeview1000** [comment]
> > Same issue, I uninstalled and reinstalled many times. The binaries are in the right place and even works when you create a new database, but the old one the mysql binaries are crashing, the new one they stay running. Are there any logs or anything to see why these are crashing?
> 
> There should be a log located in the database's data folder (Right click on database -> Open data directory). For MySQL it should be named `mysqld.local.err`. Can you check that and provide me with what you see?

2025-08-19T05:20:48.079683Z 1 [ERROR] [MY-012611] [InnoDB] Operating system error number 32 in a file operation.
2025-08-19T05:20:48.083694Z 1 [ERROR] [MY-012615] [InnoDB] The error means that another program is using InnoDB's files. This might be a backup or antivirus software or another instance of MySQL. Please close it to get rid of this error.
2025-08-19T22:20:34.081827Z 0 [System] [MY-015015] [Server] MySQL Server - start.
2025-08-19T22:20:34.407541Z 0 [System] [MY-010116] [Server] C:\Users\user\AppData\Local\com.tinyapp.DBngin\Binaries\mysql\8.4.2\bin\mysqld.exe (mysqld 8.4.2) starting as process 18864

But no other processes we're using the files as far as I know. I managed to get my server up and running manually with 

cd "C:\Users\user\AppData\Local\com.tinyapp.DBngin\Binaries\mysql\8.4.2\bin"
.\mysqld.exe --defaults-file="C:\databases\my-project-mysql\mysql.cnf" --console

if anyone else is desperate just to get the database open
