### ISSUE TITLE
MySQL Stuck on 'Starting...' Due to Incorrect Binaries Path on WIndows

### ISSUE THREAD

**Issue by patuh-istizhar** [TablePlus/DBngin#153]
MySQL 8.4.0
build 0.0.3 (i think) on Windows 11

I can't start MySQL because it gets stuck on 'Starting...'. When I check the MySQL database server binaries, they are pointing to C:\Users\{username}\OneDrive\Dokumen. In contrast, PostgreSQL starts successfully, and its binaries correctly point to C:\Users\{username}\AppData\Local\com.tinyapp.DBngin\Binaries\postgresql\16.4.1."

**Comment by huyphams** [comment]
Thanks, let us check it.

**Comment by huyphams** [comment]
Hi @patuh-istizhar are you using default or you custom the mysql configure file or data path?

**Comment by patuh-istizhar** [comment]
> Hi @patuh-istizhar are you using default or you custom the mysql configure file or data path?

Hi, I'm using the default configuration. I just clicked on the connection (which downloaded MySQL), and then it got stuck at the loading stage.

**Comment by patuh-istizhar** [comment]
Is there a way to perform a clean install of all configurations in DBngin? Maybe a clean install could solve this issue.

**Comment by huyphams** [comment]
Hi @patuh-istizhar  You can uninstall the app via windows uninstall/install app.

**Comment by huyphams** [comment]
The build 0.0.6 should fix this issue. Please let me know if you're still seeing the bug.
