### ISSUE TITLE
Issues after update home brew.

### ISSUE THREAD

**Issue by abkrim** [TablePlus/DBngin#155]
Hi.

I have a problem with DBngin on shell and on TablePlus Build 571

1. Driver 8.0.33

2. DBngin build number and platform build 72 in Macosx 

3. macOS 14.6.1 (23G93) M1

4. The steps to reproduce this issue:

Update brew. I have a mysql-client in brew ( inod't kno if DNEning install client but I don't see and I need a client for use with shel scripts. 

```
❯ /opt/homebrew/opt/mysql-client@8.0/bin/mysql -S /tmp/mysqlx.sock -u root -p
Enter password:
ERROR 2007 (HY000): Protocol mismatch; server version = 11, client version = 10
```  

I had to revert back to using the MySQL server installed via Homebrew (and additionally install the older version, as MySQL 8 suddenly upgraded to MySQL 9 in Homebrew). If there's any help to revert back, I would appreciate it, because I prefer to use a single mechanism.
![CleanShot 2024-09-15 at 14 24 14](https://github.com/user-attachments/assets/3239a938-d334-4ac2-b4a0-eff7c0cd8db4)
![CleanShot 2024-09-15 at 14 23 45](https://github.com/user-attachments/assets/b29e5619-c4ba-4d17-a43f-9ccafd0c22b3)

**Comment by huyphams** [comment]
Hi @abkrim i don't think DBngin can control homebrew. Maybe you can copy the data dir of mysql in brew and then setup a database with DBngin with that data? (Stop using homebrew)

**Comment by abkrim** [comment]
Oh. I see my mistake...

In zshrc has a part use for mysql in ptah `/opt/homebrew/opt/`

But after remove (Full) mysql installed from Home brew.

- Not mysql service in my compouter
```bash
ps aux|grep -i mysql
abkrim           51968   0.0  0.0 410733264   1664 s001  S+    5:45PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox -i mysql
```
- Not socket
```bash
la /tmp/
...
srwx------  1 abkrim  wheel     0B Sep 15 12:44 com.adobe.AdobeIPCBroker.ctrl-abkrim
drwx------  3 abkrim  wheel    96B Sep 15 12:43 com.apple.launchd.TCRRugNxkZ
-rw-r--r--  1 root    wheel     0B Sep 15 12:16 daemon.log
-rw-r--r--  1 abkrim  wheel     0B Sep 15 12:48 hisory.log
srwxrwxrwx  1 abkrim  wheel     0B Sep 15 12:44 ovpnconnect-local-ipc.sock
drwxr-xr-x  2 root    wheel    64B Sep 15 12:16 powerlog
srwx------  1 abkrim  wheel     0B Sep 15 12:44 redis.sock
drwxr-xr-x  3 abkrim  wheel    96B Sep 15 12:43 tableplus
```

Start mysql installed via DBNgin (clean)

![CleanShot 2024-09-15 at 17 52 51](https://github.com/user-attachments/assets/24248240-ef17-4cae-b509-ac00f5f7f725)

Start mysql with DBNgin

```bash
srwxrwxrwx  1 abkrim  wheel     0B Sep 15 17:53 mysql8033
-rw-------  1 abkrim  wheel     6B Sep 15 17:53 mysql8033.lock
srwxrwxrwx  1 abkrim  wheel     0B Sep 15 17:53 mysqlx.sock
-rw-------  1 abkrim  wheel     6B Sep 15 17:53 mysqlx.sock.lock
```

Try nconnect 

```bash
mysql -u root
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
```

![CleanShot 2024-09-15 at 17 58 36](https://github.com/user-attachments/assets/9c529db5-4453-42ba-86ab-79138c646914)

I've been using TablePlus for over two years, and this is the first time I've had a problem with DBngin.

I'm installing MySQL and restoring my backups because I have to hand in a project tomorrow.
Otherwise I'd spend a little more time on this problem.

**Comment by huyphams** [comment]
I think you should use the full path of the socket8033. There is no way that MySQL knows your custom socket path. They know the default mysql.sock because it's hard-coded in their code.

<img width="798" alt="Screenshot 2024-09-16 at 10 34 23 AM" src="https://github.com/user-attachments/assets/7f0f7e34-10a7-41c3-9185-77f15e3070e8">

**Comment by huyphams** [comment]
Or you can use the port, not socket.
