### ISSUE TITLE
When I start DBngin, I get the following error

### ISSUE THREAD

**Issue by wjthomas9** [TablePlus/DBngin#16]
Please fill out the detail below, it helps me investigate the bug:

I get the following error when trying to add a database server in DBngin: "DBngin needs internet in order to load database listing"

1. Driver (Ex: PostgreSQL 10.0): PostgreSQL 11.1

2. DBngin build number: 1.0 (build 14)

3. macOS version: 10.14.1

4. The steps to reproduce this issue:

    1. Launch DBngin
    2. Click + button to create new database server

<img width="532" alt="screen shot 2018-11-30 at 11 18 39 am" src="https://user-images.githubusercontent.com/986696/49304352-b772f600-f491-11e8-8902-4b5e99cd6b30.png">

**Comment by huyphams** [comment]
DBngin needs networking to pull the list of the driver. This popup will show if it is failed to connect to the server. Can you try it again?

**Comment by wjthomas9** [comment]
Looks like it was our firewall/proxy stuff. I was able to connect over LTE, but some proxy settings in the future may not hurt. Thanks!
