### ISSUE TITLE
PostgreSQL extension uuid-ossp not found

### ISSUE THREAD

**Issue by wiput1999** [TablePlus/DBngin#20]
Please fill out the detail below, it helps me investigate the bug:

1. Driver (Ex: PostgreSQL 10.0):
PostgreSQL 10.5
2. DBngin build number:
Version 1.0 (14)
3. macOS version:
10.14.2
4. The steps to reproduce this issue:
- RUN CREATE EXTENSION "uuid-ossp";
Then error
```
ERROR:  could not open extension control file "/Users/Shared/DBngin/postgresql/10.5/share/extension/uuid-ossp.control": No such file or directory
```

**Comment by insanrizky** [comment]
@wiput1999, how did it be resolved?
