### ISSUE TITLE
After installing app and adding a mysql 8 server, I can't connect to server.

### ISSUE THREAD

**Issue by brileyd** [TablePlus/DBngin#21]
Please fill out the detail below, it helps me investigate the bug:

1. Driver (Ex: PostgreSQL 10.0): MySQL 8.0.12

2. DBngin build number: 1.0 (14)

3. macOS version: 10.13.6

4. The steps to reproduce this issue:

a. Install DBngin and start the app.
b. Select the plus sign "+" in the top-right to add a server.
c. Name the server MySQL8 and select Sevice: MySQL and Version: 8.0.12.
d. Click the start button for the newly added server (everything shows it was started).
e. Press Command+T to open Terminal.

At this point the terminal will show "You need to install database server first" and entering mysql at the prompt will return the error: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

**Comment by brileyd** [comment]
Never mind, I found that I had an older MySQL version installed from Brew that was on my path and it was trying to use the executable from it.  I needed to use the executable at Users/Shared/DBngin/mysql/8.0.12/bin/.  Also, I needed to use root as the user and an empty password.

Thanks!!!

**Comment by rampanwar** [comment]
Details:
1. Driver: MySQL 8.0.12
2. DBngin build number: 1.0 (16)
3. macOS version: 10.14
4. steps to reproduce: 
- Install DBngin and start the app.
- Add a server, Name the server MySQL8 and select Service: MySQL Version: 8.0.12, set Port: 3308
- Start the new server, works fine so far.
- Note that, there is another MySQL server Version: 5.6.7 running installed via brew. I can find both of these server connections in MySQL workbentch and properly interact.
- I have a PHP Yii 1.1.13 application running on MacOS Mojave 10.14 with default provided Apache 2.4 and PHP 7.1.19
DB connection component in Yii1.1
`'db'=>array(
	'class'=>'DbComponent',
	'connectionString' => 'mysql:host=localhost;port=3308;dbname=dbName',
	'emulatePrepare' => true,
	'username' => 'root',
	'password' => 'R@nd0mP@s5wOrd',
	'charset'=>'UTF8',
),`

It fails to connect and returned error is:
**CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No such file or directory**
So next, I changed default socket (PDO and mysqli) in php.ini to /tmp/mysql_3308.sock, and error changed to:
**CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client**

What am I missing?

**Comment by huyphams** [comment]
Maybe the Yii framework doesn't support MySQL 8, I think it uses old lib of MySQL.
