### ISSUE TITLE
PHP serialize data doesn't display correctly

### ISSUE THREAD

**Issue by simonhamp** [TablePlus/DBngin#25]
1. Driver (Ex: PostgreSQL 10.0):
MySQL 5.x, MySQL 8.x

2. DBngin build number:
MariaDB 10.1.30, MySQL 5.7.22, MySQL 8.0.13

3. macOS version:
10.14.3

4. The steps to reproduce this issue:
Write a PHP-serialized object to a database (e.g. `serialize(new stdClass)`). Observe the serialized string is cut off in TablePlus:
<img width="305" alt="Screenshot 2019-03-09 at 18 24 56" src="https://user-images.githubusercontent.com/31628/54075547-ac054700-4298-11e9-957f-f89bde8e6ea0.png">

But if you connect directly to mysql and query for that data, it will be complete.

**Comment by huyphams** [comment]
Hi @simonhamp how is this issue related to DBngin, could you please explain it? thanks!

**Comment by simonhamp** [comment]
Apologies! I posted in the wrong repo!
