### ISSUE TITLE
can't use terminal.app

### ISSUE THREAD

**Issue by voody77** [TablePlus/DBngin#27]
Please fill out the detail below, it helps me investigate the bug:

1. Driver (PostgreSQL 11.0):

2. DBngin build number: 1.0(16)

3. macOS version: 10.14.4

4. The steps to reproduce this issue: 
<img width="406" alt="image" src="https://user-images.githubusercontent.com/5172563/55713827-23460c00-59fa-11e9-8c05-6529f9870b01.png">

Can't use terminal.app to setup db

**Comment by voody77** [comment]
Hello!
When to expect fix?

**Comment by huyphams** [comment]
We're going to release a new version next week @voody77, thank you for reminding me.
