### ISSUE TITLE
How can I disable strict mode in MySQL?

### ISSUE THREAD

**Issue by 4unkur** [TablePlus/DBngin#35]
I tried to create a file with single line:
```
sql_mode = ''
```
and use that file as a custom config for MySQL 5.7 service.
After that change MySQL stopped working so I removed that config file.
How can I disable strict mode?

**Comment by huyphams** [comment]
Please follow the MySQL documents @4unkur 
https://dev.mysql.com/doc/refman/8.0/en/option-files.html
it should be:
[mysqld]
```
sql_mode = "SOMETHING"
```

**Comment by 4unkur** [comment]
@huyphams great, thanks.
