### ISSUE TITLE
Finderbar support

### ISSUE THREAD

**Issue by timreichen** [TablePlus/DBngin#36]
I am really happy with this app but I wonder if there will be finderbar support for it. It would be a nice feature to just start and stop services from the finder without opening the app as a window.

Are there any plans for this?

**Comment by huyphams** [comment]
Hi @timreichen thank you, yep, we will support the menu bar in the future release.

**Comment by zengxs** [comment]
Support the menu bar is an awesome feature.
And more, I hope DBngin can be hidden from Dock in the future, like the Postgres.app.

**Comment by iamvinny** [comment]
Any news on this?

**Comment by crezra** [comment]
bump on this particular feature, any updates on whether it's on the roadmap ?

**Comment by huyphams** [comment]
We're implementing it, will be ready on the next update!

**Comment by huyphams** [comment]
Just tick on Start on login + open on the menu bar you can close the app and remove the dock shortcut if you like.
