### ISSUE TITLE
Import existing db files from homebrew

### ISSUE THREAD

**Issue by tanthammar** [TablePlus/DBngin#37]
I had mySql installed with homebrew and I used Sequel Pro to manage my db:s.
Have a lot of existing db files in /usr/local/var/mysql/

Now that I switched to DBngin/Table Plus, is there a way to move these files and reuse them with this setup. (I did not do any sql dumps before uninstalling mySql w Homebrow)

Can't find where the db files are stored from DBngin.

All db:s are in mySql 5.7 format.

**Comment by huyphams** [comment]
The best way to move the databases is backup/restore, you can connect to the old database => backup it.
Open DBngin, create a new MySQL Server with a different port => restore the database.

**Comment by tanthammar** [comment]
I tried a different port but got errors on every port I tried to use. Can you help me suggest a port that can co-exist with 3306, that Homebrew allocates to its db.

**Comment by huyphams** [comment]
Can you post the error message here @tanthammar thanks

**Comment by tanthammar** [comment]
Restarted my computer, any port worked fine after that :) sorry for the inconvenience.
