### ISSUE TITLE
What is the default username and password?

### ISSUE THREAD

**Issue by stevenmc** [TablePlus/DBngin#43]
What is the default username and password for MySQL instances?

**Comment by stevenmc** [comment]
Username: root
Password: blank
Host: 127.0.0.1

**Comment by AxelPariss** [comment]
When I create a Postgres database, it's : 

- user : `postgres`
- password : `` (empty)
- database : `postgres`

**Comment by ranjithrd** [comment]
Can this be added as an alert when you create the postgres database, or for that matter, any database, so it's easier? Thanks.
