### ISSUE TITLE
Need an option to run the service on startup

### ISSUE THREAD

**Issue by ghost** [TablePlus/DBngin#46]
Its a request for enhancement not an issue, that will be great if you put an option to run the server service on startup, for now I must run the services manually from DBngin each time I restart the OS

**Comment by jarrodparkes** [comment]
yes please

**Comment by fkxstyle** [comment]
any workaround so far? like a command or something

**Comment by ryatkins** [comment]
+1 - would love this feature

**Comment by obsergiu** [comment]
+1

**Comment by genericmilk** [comment]
+1 Absolutely, It's all that's standing in the way of me ditching community server!

**Comment by egkrinkel** [comment]
+1

**Comment by bonny** [comment]
This is possible since [Build 52](https://github.com/TablePlus/DBngin/wiki/Changelogs#build-52---new-feature-and-bug-fixes).
