### ISSUE TITLE
Unable to connect to MySQL 5 db using password from terminal

### ISSUE THREAD

**Issue by texastoast** [TablePlus/DBngin#53]
Please fill out the detail below, it helps me investigate the bug:

1. Driver: MySQL 5.7.23

2. DBngin build number: 3.1 (32)

3. macOS version: 10.15.7

4. The steps to reproduce this issue:

- Create a new MySQL 5.7 database
- Connect with TablesPlus and give the root user a password
- In terminal, run `mysql -S /tmp/mysql_3306.sock -u root -p`
- Enter root user password when prompted
- Error returned: 'ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)'

 The problem persists with non-root users as well. EG: create a user and database, give user full permissions on database, try to login from terminal. The same error is returned.

**Comment by huyphams** [comment]
Hi @texastoast there is no password so you can omit the -p params.

**Comment by huyphams** [comment]
If you want to create a password, you can just log in with root and then alter the root password. However, it's the local database we would recommend you leave it as it is.
Another solution is you can download our app https://tableplus.com it would allow you to create/alter user password easily. (this feature is free).

**Comment by texastoast** [comment]
You misunderstand. I'm already using tablesplus, as noted in the original post.

When I give the root user a password, I can no longer connect to the server via the command line using the password I just configured.

When I create a new user and give that user a password and then grant that user full permissions on a database, I can not connect to that database via the command line using that user and password.

**Comment by texastoast** [comment]
Closing. This issues was due to having multiple versions of mysql installed and not exporting the environment variables to the terminal using DBngin. Once I removed all other versions of MySQL and exported the env, everything worked as expected. Thank you.
