### ISSUE TITLE
Compatibility with Rosetta 2

### ISSUE THREAD

**Issue by koriym** [TablePlus/DBngin#54]
Please fill out the detail below, it helps me investigate the bug:

1. Driver (Ex: PostgreSQL 10.0):

Redis 5.0.9

2. DBngin build number:

Version 3.1 (32)

3. macOS version:

Big Sur (M1)

4. The steps to reproduce this issue:

I can't start Redis on Apple Silicon Mac Rosseta 2.

**Comment by AlexMartinFR** [comment]
I'm on a M1 MacBook Air right now, tried just that and could run Redis just fine.
Same version as you.

<img width="652" alt="Capture d’écran 2020-11-26 à 02 06 23" src="https://user-images.githubusercontent.com/19224681/100296251-fe662a00-2f8b-11eb-84c5-85e94f6346c8.png">
 
Is there any other step to reproduce the issue?

**Comment by koriym** [comment]
Could you click "retry serve list" and confirm still running?

**Comment by koriym** [comment]
Could you click "reload server list" and confirm still running?

**Comment by huyphams** [comment]
Looks like it was a Redis issue: https://github.com/redis/redis/issues/8062
There are two options:

1. We have to wait for the official Redis release.
2. I can build the hot-patch Redis but it may be unstable.

I will probably do 2 at weekend.

**Comment by AlexMartinFR** [comment]
After reloading the server list, I can confirm the issue 👍

**Comment by canerdogan** [comment]
@huyphams is there any update on this?

Thanks 👍

**Comment by StanBarrows** [comment]
It looks like they have fixed it within the latest release. Can we support you somehow @huyphams ?

`FYI, this bug is fixed in Redis 6.0.10 and 6.2 RC2`

_Originally posted by @oranagra in https://github.com/redis/redis/issues/8062#issuecomment-762738194_

**Comment by isfinn** [comment]
Same here.

**Comment by nessor** [comment]
Can confirm. A workaround for the moment is
```
brew install redis
brew services start redis
```

**Comment by huyphams** [comment]
Please install DBngin 34 or install Redis 6 , it's supported rosetta now. Thank you.
