### ISSUE TITLE
DBngin could not access /Users/Shared/DBngin

### ISSUE THREAD

**Issue by jinghui70** [TablePlus/DBngin#6]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySql 5.7.23

2. Which DBngin build number are you using:
1.0(10)

3. The steps to reproduce this issue:
when start a new mysql, after showing "Downloading binaries...0%" for a while, it says "DBngin could not access /Users/Shared/DBngin, please click the help button on the tool bar and fire an issue."

**Comment by huyphams** [comment]
Hi @jinghui70 thanks. could you tell me which the macOS version are you using?

**Comment by jinghui70** [comment]
> Hi @jinghui70 thanks. could you tell me which the macOS version are you using?

10.13.6 (17G65) 。
I download 5.7.23.zip from 
https://s3.amazonaws.com/dbngin-binaries/mysql/5.7.23.zip and extract to ~/Library/Application Support/com.tinyapp.DBngin/Binaries/mysql, it works

**Comment by huyphams** [comment]
Yep, I think the DBngin had failed to download the binary. MySQL 8.0 and PostgreSQL 10 were included in the app so it can't be failed.

**Comment by phoenixg** [comment]
Same issue:

1. Driver 

mysql 5.7.x

2. DBngin build number:

Version 1.1 (20)

3. macOS version:
macOS Mojave 10.14.2 (18C54)

4. The steps to reproduce this issue:

Just Download the MySQL 5.7

```
DBngin could not access /Users/Shared/DBngin, please click the help button on the tool bar and fire an issue.
```
