### ISSUE TITLE
Update for Apple Silicon M1 machines

### ISSUE THREAD

**Issue by Harry-Harrison** [TablePlus/DBngin#61]
**macOS version:** 11.2.1

This isnt a bug exactly, but a feature request. It'd be great if the DBngin could be updated for M1 machines. I'm not going to pretend to know what that'd entail in terms of supporting the database packages, but I can see that it requires Rosetta 2 to run currently whereas TablePlus does not.

![image](https://user-images.githubusercontent.com/140605/109528828-fea32380-7aac-11eb-874a-b5d99555d706.png)

**Comment by huyphams** [comment]
It's supported now. Please update to the build 34, thanks!

**Comment by gravataLonga** [comment]
@huyphams Mmm, its only running native application it self, but binary of database is not running on native M1.  

<img width="1552" alt="Screenshot 2021-09-21 at 22 10 02" src="https://user-images.githubusercontent.com/1126525/134248297-edc64bf0-99fe-4286-a3ec-34b7536ea423.png">

**Comment by Harry-Harrison** [comment]
@gravataLonga Looks like M1 compatible Mysqld is only possible through installing with Brew at the moment potentially.

**Comment by huyphams** [comment]
wow thanks @Harry-Harrison for letting me know that MySQL is ready for M1. We will add it in the next update!

**Comment by gravataLonga** [comment]
@Harry-Harrison exactly what I mean! You can have Mysqld native on M1. ;) @huyphams Thank for make effort to integrate native mysqld into your application!
