### ISSUE TITLE
large engine folder, binlog

### ISSUE THREAD

**Issue by anditsung** [TablePlus/DBngin#66]
<img width="712" alt="Screen Shot 2021-06-12 at 09 16 35" src="https://user-images.githubusercontent.com/1090413/121762236-e5efe280-cb5e-11eb-90d2-90832b09b8d3.png">

i have a lot of this file
the folder size is 40gb
is it save to delete binlog file?

**Comment by colonelclick** [comment]
Yes, you can delete the binlogs ending in numbers. You can also prevent them from being created by adding a line to your my.cnf file. The syntax below is for 8.x, your version may have a different syntax. There are also options to limit the size if you do not wish to disable them entirely.

```
[mysqld]
disable_log_bin
```

**Comment by huyphams** [comment]
We've added the disable bin log option, it will be available in the next update!
<img width="532" alt="Screen Shot 2022-01-04 at 6 59 49 PM" src="https://user-images.githubusercontent.com/3654622/148055977-9dcedfaf-229e-4c05-8690-668a943f7e98.png">

**Comment by huyphams** [comment]
If you don't want to wait for the release, please download the hotpatch here: https://www.dropbox.com/s/sz5xmnakr27n52o/DBngin.dmg?dl=0
