### ISSUE TITLE
Can't connect to database using Sequel Pro

### ISSUE THREAD

**Issue by JayteeNZ** [TablePlus/DBngin#67]
Seems like either this is a proprietary app with Table Plus, or something is off. If it's proprietary then i'll just remove both, as not a fan of Table Plus.

Using the normal credentials (127.0.01, u: root) and get connection failed. Hop into TablePlus and she fires up right away.

**Comment by huyphams** [comment]
We do not manipulate MySQL to make it just work on TablePlus. There is nothing wrong with it except Sequel Pro does not support MySQL 8.0

You can go to appstore and download Sequel Ace as it is the active fork of Sequel Pro (as far as I know)
