### ISSUE TITLE
Can't find database

### ISSUE THREAD

**Issue by djmtype** [TablePlus/DBngin#71]
Please fill out the detail below, it helps me investigate the bug:

1. Driver (Ex: PostgreSQL 10.0): MySQL 5.7.23

2. DBngin build number: 3.4

3. macOS version: 11.5.2

4. The steps to reproduce this issue: 
I know there's a quicklink to the database from DBngin to TablePlus. However, if I open TablePlus and try to access it from there by entering my database name on port 3306, with username root and no password, it says it can't be found. This means when I try to install Strapi with MySQL option, it won't work.

- Start DBngin
- Activate or enable the database I previously set up using DBngin
- Open TablePlus
- Create new connection 
- Choose MySQL
- Add the same database name set up in DBngin
- Add 127.0.0.1 as host
- Add username as "root"
- Leave password empty
- Set up same port number as in DBngin
- Test Connection

Get unknown database error

**Comment by huyphams** [comment]
Hi @djmtype Could you show me the connection form in TablePlus?

**Comment by djmtype** [comment]
Maybe a better question is where does DBngin store the databases created by it?

**Comment by djmtype** [comment]
![Screen Shot 2021-09-05 at 1 17 49 PM](https://user-images.githubusercontent.com/930713/132135666-2b3c4334-97f9-49f9-bf8e-a38fbd26bd63.png)

**Comment by huyphams** [comment]
How did you create that database? the strapi?

**Comment by djmtype** [comment]
@huyphams I created it using DBngin.

**Comment by huyphams** [comment]
I don't think that you did it right. The name is the label for that server, it's not the database.

You must connect to the database and create it by command `create database` or click the database button and create it from GUI.

**Comment by djmtype** [comment]
I'm not sure it matters but the MySQL build DBngin downloads/installs is Intel-based instead of ARM.

**Comment by huyphams** [comment]
You can create a database within TablePlus by clicking the database button in the image below:
<img width="274" alt="Screen Shot 2021-09-06 at 12 28 42 AM" src="https://user-images.githubusercontent.com/3654622/132135937-c72545fe-4725-48cc-b88f-fec87414e0ed.png">

**Comment by djmtype** [comment]
> I don't think that you did it right. The name is the label for that server, it's not the database.
> 
> You must connect to the database and create it by command `create database` or click the database button and create it from GUI. Then you will be able to connect it with `strapi`
> 
> You can leave the database field empty in order to connect to the server.

Ok, thanks, I completely misinterpreted the instructions. By creating the connection, I also thought it was setting up a database. I've been living in Local (by Flywheel) too long.
