### ISSUE TITLE
How to see homebrew services in DBngin

### ISSUE THREAD

**Issue by pleaz** [TablePlus/DBngin#73]
Please fill out the detail below, it helps me investigate the bug:

1. Driver (Ex: PostgreSQL 10.0): homebrew

2. DBngin build number: 4.0 (42)

3. macOS version: 12.0.1  arm

4. The steps to reproduce this issue:

I  have  installed homebrew with php-fpm and other services, but I can't see them in DBngin, it's not what I should expect here, but I saw that in many sceenshoots from other users

**Comment by mpadev** [comment]
I have the same issue, after moving to a new mac (12.1 arm). On my old mac there used to be a Homebrew services section

**Comment by jamesclavel** [comment]
+1 on this. Installed using homebrew MariaDB PHP7.4 (php-fpm) - all for ARM arch (m1 mac) - but can't see homebrew services. SequelAce can connect via localhost though.

**Comment by vdhruv** [comment]
+1 I am also not able to see homebrew services on M1 Pro.

**Comment by Dectom** [comment]
Same issue here, I have 2 friends that I got to install DBNgin and they both have it, I didn't know it was a feature until they Installed it :( 

They are both Intel, I'm M1

**Comment by LucaCassietti** [comment]
+1 
Any updates?

**Comment by huyphams** [comment]
Hi this issue has nothing to do with DBngin, if you have homebrew service installed on your macOS, you will see the homebrew section in the app.

**Comment by huyphams** [comment]
Hi @vdhruv I found the issue. gonna fix it now.

**Comment by huyphams** [comment]
Hi guys, please find the hot patch in the link below: https://www.dropbox.com/s/sz5xmnakr27n52o/DBngin.dmg?dl=0
Please let me know if you are still seeing the issue.
Thank you!

**Comment by vdhruv** [comment]
Thank you @huyphams

Working now.

**Comment by Dectom** [comment]
When will this be merged into the app?

**Comment by huyphams** [comment]
Yes, please update to the newest release

**Comment by liamseys** [comment]
I see the services from Homebrew but they show as offline while PHP and Nginx are just running.

**Comment by huyphams** [comment]
Hi @liamseys could you run this command and tell me the result, please?

brew services list

**Comment by liamseys** [comment]
@huyphams It shows as status 'none', it only shows as started if I run it as root. This describes my issue:

https://github.com/laravel/valet/discussions/1146

**Comment by liamseys** [comment]
```
➜  ~ brew services list
Name    Status User File
dnsmasq none   root
nginx   none   root
php     none   root
```

**Comment by huyphams** [comment]
So I think this issue is a valet issue because it's using root. DBngin could not use root, so it is not possible to get the correct status.

**Comment by wivaku** [comment]
Using DBngin 6.2 and also not seeing any homebrew services on my M2 laptop.
Everything is fine on my Intel based iMac.  
Similar services list on both.

E.g. on my iMac:
```
Name    Status User File
caddy   none
dbus    none
dnsmasq none   root
mailhog none
mariadb none
nginx   none   root
php     none   root
php@8.1 none
unbound none
```

DBngin shows all of these on my iMac, also the _root_ ones. And shows nothing on my M2 laptop.  
Difference I can think of: for Apple silicon systems the homebrew root is `/opt/home` instead of `/usr/local/`.
