### ISSUE TITLE
Backup doesn't work in Tableplus when database was created with DBngin

### ISSUE THREAD

**Issue by peckanthony** [TablePlus/DBngin#74]
1. Driver (Ex: PostgreSQL 10.0):
MySQL 5.7.23
2. DBngin build number:
Version 4.0 (42)
3. macOS version:
Monterey 12.0.1 (21A559)
4. The steps to reproduce this issue:
- Create new database with DBNgin with different port than 3306 (3308 in my case)
- Add the database as a new connection in TablePlus
- Connect to the created database with the default root user without password
- Try to backup a database via File > Backup

This doesn't work because the backup command always tries with password (Use password = YES). I get the same error on the command line, when trying to connect.

I fixed this by creating a new user with a password (admin/admin), connecting with that user and backing up my database.

Perhaps consider an option when creating a new database in DBngin to give the user a password? root/root?

**Comment by huyphams** [comment]
Hi, I don't think it is a DBngin issue. It's a TablePlus issue (maybe very old build).
