### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by xartuu** [TablePlus/DBngin#75]
_DBngin_ is a useful tool in a simple graphic design. It certainly speeds up work for many developers.

According to statistics, Windows is the largest operating system, used by as many as [75.18%](https://gs.statcounter.com/os-market-share/desktop/worldwide) of desktop users. 
**So please add support for Windows.**

**Comment by fieu** [comment]
> Windows is the largest operating system, used by as many as 75.18% of desktop users.
Not development machines for sure.

**Comment by Dectom** [comment]
I use MacOS and Windows, having this tool on windows would be 100% the best tool and make life a lot easier

**Comment by xartuu** [comment]
> I use MacOS and Windows, having this tool on windows would be 100% the best tool and make life a lot easier

That is exactly what I believe!


I apologize for not referring to the previous message.
> Not development machines for sure.

They may not be, but that doesn't mean developers aren't working on them. If only because of the vastness of applications, games or useful programs.  This windows program would make life easier for many developers. That's why I suggested creating a windows version.

**Comment by xitude** [comment]
Not sure if this helps but its pretty close - https://www.statista.com/statistics/869211/worldwide-software-development-operating-system/

**Comment by huyphams** [comment]
Let me see if we can bring it to Windows. We will give it a try

**Comment by alxdrlitreev** [comment]
Would be fantastic to have it on Windows too. Is there any progress on that, @huyphams?

**Comment by Petoches** [comment]
Still no plan for a windows release ?

**Comment by jan-heise** [comment]
> Let me see if we can bring it to Windows. We will give it a try

Is there any update?

**Comment by FlusherDock1** [comment]
> Let me see if we can bring it to Windows. We will give it a try

Any updates?

**Comment by huyphams** [comment]
We're doing it right now

**Comment by endrit-mesh** [comment]
> We're doing it right now
Amazing! 
By any chance do you know when it will be released?

**Comment by AnaelBonnafous** [comment]
It's now available at https://dbngin.com 👍

**Comment by xartuu** [comment]
Great news! 🎉
