### ISSUE TITLE
Mysql 5.7 on M1(ARM) Macbook

### ISSUE THREAD

**Issue by mitchjam** [TablePlus/DBngin#79]
1. Driver (Ex: PostgreSQL 10.0): **Mysql 5.7**

2. DBngin build number: **Version 4.0 (42)**

3. macOS version: **Montery 12.1**

4. The steps to reproduce this issue: 
  - Install MySQL 5.7
  - click 'Start'
  - DBngin crashes

**Comment by LinusGeffarth** [comment]
doesn't crash for me, but also can't connect to it even though it's _started_

**Comment by robbis95** [comment]
Doesn't work for me either M1 Macbook Pro

**Comment by huyphams** [comment]
HI, the 5.7 is not a native ARM. please use the MySQL 8
If you want to use the 5.7 please install rosetta 2 first.
