### ISSUE TITLE
[How to] Create custom config file for mysql server?

### ISSUE THREAD

**Issue by d3bj** [TablePlus/DBngin#81]
How can I setup mysql 8 compatibility with mysql 5 programmes? I would love to set up config but did not found any example for how to create a config for that.
Please fill out the detail below, it helps me investigate the bug:

1. Driver (Ex: PostgreSQL 10.0): 
MySQL 8.0.19
3. DBngin build number:
Latests as of 05-03-2022
4. macOS version:
12
5. The steps to reproduce this issue:
+ > Config

**Comment by huyphams** [comment]
Hi @d3bj you could read the MySQL documents it will show you the config syntax.
