### ISSUE TITLE
Can't connect to DB on 127.0.0.1 (61)

### ISSUE THREAD

**Issue by SagittariusITG** [TablePlus/DBngin#83]
Please fill out the detail below, it helps me investigate the bug:

1. Driver (Ex: PostgreSQL 10.0): PostgreSQL 10.0

2. DBngin build number: Version 4.1 (46)

3. macOS version: Monterey 12.3.1

4. The steps to reproduce this issue: https://gyazo.com/cfe43d36e0a029ea64025c1555968c7e It says me that, can someone help me please? It happend suddenly.

**Comment by huyphams** [comment]
Hi @SagittariusITG that is not the step to reproduce the issue. Could you please show me the connection form info?

**Comment by huyphams** [comment]
Did you using any proxy, such as Cloudflare Warp? Have you tried to restart the database server in dbngin?

**Comment by SagittariusITG** [comment]
No, i'm not using any proxy and yes, i've tried to reload the database and the computer as well but it says me the same

**Comment by huyphams** [comment]
Please open the database folder, and find the file mysqld.local.err please open that file to see the issue.

<img width="398" alt="Screen Shot 2022-05-12 at 10 58 55 AM" src="https://user-images.githubusercontent.com/3654622/167989268-c286ed57-9af5-4a91-8477-a8204a086463.png">
