### ISSUE TITLE
Request Feature: menu bar app.

### ISSUE THREAD

**Issue by pys1992** [TablePlus/DBngin#87]
Hi, is there any plan to support running DBngin on menu bar?

**Comment by maarten00** [comment]
This would be great. As someone who uses cmd+tab a lot, it's a bit annoying to have a 'background app' like DBngin in your app list. (And Dock, for whoever uses that) It would be great if it was possible to send this app to the menu bar, MAMP also allows you to toggle menu bar only on/off.

**Comment by huyphams** [comment]
WIP.

**Comment by andreas-bergstrom** [comment]
https://github.com/TablePlus/DBngin/issues/89

**Comment by maarten00** [comment]
Wow, this is amazing! Thanks so much! 
Would it be possible to hide the app from the dock when running in 'menu bar mode' and/or after closing the window? Other apps like Docker do this as well.

**Comment by maarten00** [comment]
@huyphams great, that works as expected. Thanks!
