### ISSUE TITLE
feature suggestion: menubar item

### ISSUE THREAD

**Issue by selfagency** [TablePlus/DBngin#9]
love the app as it's a great replacement for [launchrocket](https://github.com/jimbojsb/launchrocket) which stopped working in the previous mac os release. it would be even better, imho, if there was an option to use it as a menubar item and launch on start and not just as a windowed application.

**Comment by huyphams** [comment]
Menu bar app is already in our roadmap 😄

**Comment by selfagency** [comment]
k thx
