### ISSUE TITLE
Start on Login is not launching services on machine startup

### ISSUE THREAD

**Issue by andriihorpenko** [TablePlus/DBngin#94]
Please fill out the detail below, it helps me investigate the bug:

1. Driver (Ex: PostgreSQL 10.0): Any

2. DBngin build number: 6.0 (60)

3. macOS version: Ventura 13.0.1, MacBook Pro M1 Max

4. The steps to reproduce this issue:
- Right click on a service
- Click "Edit"
- Toggle "Automatically start service on Login"
- Restart machine
- Open DBgin menu bar and see that services are not launched, even though it says "Start on Login".

The screenshot below demonstrates the state of DBngin after machine has started. As we can see, DBngin started itself, but selected services for auto-launch are not launched.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/13716167/204259612-05d62a2c-5b5b-4082-854c-e2165ee7e22d.png">

**Comment by NadsonKT** [comment]
same problem here, waiting for a solution 🙏

**Comment by huyphams** [comment]
What version of DBngin are you using @NadsonKT ?

**Comment by florianbouvot** [comment]
Same for me on a new MacBook Air M4 with DBngin 7.9 / MariaDB 10.11.6_arm.
Any idea ?
