### ISSUE TITLE
Toolbar customization persistance

### ISSUE THREAD

**Issue by HadrienX** [TablePlus/DBngin#95]
The toolbar does not save your changes. When you quit the app all your changes are lost once you reopen it.

1. Driver (Ex: PostgreSQL 10.0): N/A

2. DBngin build number: Version 6.0 (60)

3. macOS version: macOS Ventura 13.0.1

4. The steps to reproduce this issue:

- Right click on top of the app and choose "Customize toolbar".
- Reorder or remove elements to make layout different than the default one
- Quit the app and launch again, all the changes you have made disappear and the default layout is back

**Comment by pr4xx** [comment]
Seems like no config changes will be persisted at all. I tried changing ports for mysql and redis. After quitting and restarting the app the defaults are back again.

**Comment by huyphams** [comment]
It's fixed now. Thanks
