### ISSUE TITLE
Question - does it run natively on the machine

### ISSUE THREAD

**Issue by pdaus1405** [TablePlus/DBngin#97]
I just have a question as I have not found any information on this.

Are the services running directly on the machine (MacBook) or in some kind of Docker container?

best regards

**Comment by huyphams** [comment]
Hi @pdaus1405 it run directly on computer without any dependencies 
<img width="1120" alt="Screenshot 2023-02-09 at 7 58 24 AM" src="https://user-images.githubusercontent.com/3654622/217687027-a3335dbd-d04c-4171-a0b5-c735c73298e5.png">
